name: Cloud Security Simulation

on:
  push:
    branches:
      - master

jobs:
  security_attack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want to use

      - name: Install Dependencies
        run: |
          npm install

      - name: Start the Vulnerable App
        run: |
          nohup node app.js &  # Run the app in the background

      - name: Simulate SQL Injection (Example)
        run: |
          echo "Simulating SQL Injection..."
          curl -X POST "http://localhost:3000/login" -d "username=admin' OR 1=1 --&password="

      - name: Scan for Secrets (API Keys, Passwords)
        uses: zricethezav/gitleaks-action@v2

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: "http://localhost:3000"

      - name: Run Trivy Scan (Check for Vulnerable Dependencies)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "node:v16"

      - name: Log Findings
        run: |
          echo "Security vulnerabilities detected. Review the logs for details."
